sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t jliebenberg/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jliebenberg/docker-react npm run test -- --coverage
    
#script:
# - docker run USERNAME/docker-react npm run test -- --coverage
#script:
#  - docker run -e CI=true USERNAME/docker-react npm run test